//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploSeparandoEmClasses.Vetor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExemploSeparandoEmClasses.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Física.
        /// </summary>
        public static string fisica {
            get {
                return ResourceManager.GetString("fisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História.
        /// </summary>
        public static string historia {
            get {
                return ResourceManager.GetString("historia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lógica e Algoritmos.
        /// </summary>
        public static string logicaAlgoritmos {
            get {
                return ResourceManager.GetString("logicaAlgoritmos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matemática.
        /// </summary>
        public static string matematica {
            get {
                return ResourceManager.GetString("matematica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string portugues {
            get {
                return ResourceManager.GetString("portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Química.
        /// </summary>
        public static string quimica {
            get {
                return ResourceManager.GetString("quimica", resourceCulture);
            }
        }
    }
}
